apiVersion: composition.krateo.io/v1-0-0
kind: Pbi
metadata:
  annotations:
    krateo.io/connector-verbose: "true"
    meta.helm.sh/release-namespace: krateo-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: instance1
  namespace: demo-system
spec:
  environments: "dev"
  tickets: "ticket1"