{{- if eq (include "fireworks-app.ticket-version" $ | int) 1 }}
{{- range $ticket := .Values.tickets }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-jira-{{ $ticket.id }}
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: {{ $ticket.id }}
  title: {{ $ticket.title }}
  body: {{ $ticket.body }}
  status: ""
{{- end }}
{{- end }}