{{- if eq (include "fireworks-app.ticket-version" $ | int) 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-jira-{{ .Values.tickets }}
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  title: {{ .Values.tickets }}
  status: ""
...
{{- end }}