{{- if eq (include "fireworks-app.ticket-version" $ | int) 3 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-jira-ticket2
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ticket2
  title: title2
  body: body2
  status: ""
...
{{- end }}