{{- if eq (include "fireworks-app.ticket-version" $ | int) 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-jira-ticket1
  namespace: demo-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ticket1
  title: title1
  body: body1
  status: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-jira-ticket2
  namespace: demo-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ticket2
  title: title2
  body: body2
  status: ""
...
{{- end }}